version: "3.9"
services:
  helloapi:
    build:
      context: .
      dockerfile: ./Dockerfile.hello
    container_name: helloapi
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:8080
    ports:
      - "5050:8080"
    networks:
      - appnet

  timeapi:
    build:
      context: .
      dockerfile: ./Dockerfile.time
    container_name: timeapi
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:8080
    ports:
      - "5052:8080"
    networks:
      - appnet

  

networks:
  appnet:
    driver: bridge