# build
FROM --platform=$BUILDPLATFORM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY TimeApi/TimeApi.csproj ./TimeApi.csproj
RUN --mount=type=cache,target=/root/.nuget/packages dotnet restore TimeApi.csproj
COPY TimeApi/ .
RUN --mount=type=cache,target=/root/.nuget/packages dotnet publish -c Release -o /app /p:UseAppHost=false

# runtime
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime
WORKDIR /app
COPY --from=build /app .
ENV ASPNETCORE_URLS=http://0.0.0.0:8080
ENTRYPOINT ["dotnet","TimeApi.dll"]