# build
FROM --platform=$BUILDPLATFORM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY HelloApi/HelloApi.csproj ./HelloApi.csproj
RUN --mount=type=cache,target=/root/.nuget/packages dotnet restore HelloApi.csproj
COPY HelloApi/ .
RUN --mount=type=cache,target=/root/.nuget/packages dotnet publish -c Release -o /app /p:UseAppHost=false

# runtime
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime
WORKDIR /app
COPY --from=build /app .
ENV ASPNETCORE_URLS=http://0.0.0.0:8080
ENTRYPOINT ["dotnet","HelloApi.dll"]